### ISSUE TITLE
Port is grayed out in Arduino IDE 1.8.5

### ISSUE THREAD

**Issue by MNBS** [uStepper/uStepper#12]
Hello, 

I am using Arduino IDE 1.8.5. I am trying to connect the U-Stepper but the port option under tools is grayed out(as shown in the attach picture). Is there any solution for this. 

Any help would be greatly appreciated. Thank you! 

![untitled](https://user-images.githubusercontent.com/34342343/35210002-6c8d8200-ff8b-11e7-875e-f0fb3d65ac28.jpg)

**Comment by uStepperOld** [comment]
Hi! Could I get you to write on sales at uStepper.com? Then we will figure it out :)
