### ISSUE TITLE
The uStepper for arduino nano ?

### ISSUE THREAD

**Issue by annhan** [uStepper/uStepper#14]
hi, Can you help me build uStepper for arduino nano or help me write bootloader for arduino ??
I builded but my nano can't boot to main loop ( Stop ->stepper.setup)
thanks you

**Comment by uStepperOld** [comment]
Hi Annhan,

The uStepper library is build specifically for the uStepper hardware.

We do not have resources to provide support for porting the code to other hardware platforms, unfortunately.

Best Regards,
Thomas Olsen
