### ISSUE TITLE
Beginners Guide

### ISSUE THREAD

**Issue by zandeez** [uStepper/uStepper#15]
Hi Guys,

Is there any kind of beginner's guide? I have no prior experience with stepper motors or uStepper and can't get the limit detection example to work (near end limit is detected, far end is not and it continues to try spin the motor) and I have no idea why or any idea even what to look at.

I also have no idea what the different parameters for uStepper:setup are supposed to do.

**Comment by uStepperOld** [comment]
Hi Zandeez,

We don't have a specific beginner's guide. The examples are provided to give a quick overview of the functionality, along with the documentation page describing how to use each function of the library (http://ustepper.com/docs/html/)

with regards to your specific problem on the limit detect, can you write to me by email (thomas@ustepper.com), and I will try to help you get it working.

Best Regards,
Thomas Olsen
