### ISSUE TITLE
0.9 stepper using pid ?

### ISSUE THREAD

**Issue by CENTOPROJECT** [uStepper/uStepper#17]
having issue with the pid i have read the previous issue and seen that numerical 16 micro step you can change to 32 but in pid its written as text am i missing something ? pleased with product other than that :)

`void setup(void)
{
	Serial.begin(115200);
	stepper.setup(PID,THIRTYTWO,10,5,1.0,0.02,0.006)`

**Comment by uStepperOld** [comment]
due to our correspondence on facebook, i will consider this issue resolved and close this post
