### ISSUE TITLE
Missing defines in library

### ISSUE THREAD

**Issue by richardw347** [uStepper/uStepper#2]
The library refers to constants for pins DIR, STEP, ENA which are never defined as such the library and examples do not compile.

```
pinMode(DIR, OUTPUT);
pinMode(STEP, OUTPUT);
pinMode(ENA, OUTPUT);   
```

**Comment by uStepperOld** [comment]
Hi Richard 

IT sounds like you only installed the library in arduino, and not the hardware part. The three constants you refer to are not defines in the library, but constants in the hardware pin mapping file. 
Did you follow the install guide on the front page of our github page? 

Best regards, 
Thomas Olsen 

Sent from my Cyanogen phone

Den 05/04/2016 3.07 PM skrev Richard Williams notifications@github.com:

The library refers to constants for pins DIR, STEP, ENA which are never defined as such the library and examples do not compile.

pinMode(DIR, OUTPUT); pinMode(STEP, OUTPUT); pinMode(ENA, OUTPUT);

**Comment by richardw347** [comment]
Hi Thomas,

Thanks I didn't realise you has a custom board def for arduino, just downloaded the library directly!

**Comment by uStepperOld** [comment]
You are very welcome! 
Feel free to contact me again at Thomas@ustepper.com if you run into further trouble

Best regards 
Thomas Olsen 

Sent from my Cyanogen phone

Den 05/04/2016 4.37 PM skrev Richard Williams notifications@github.com:

Hi Thomas,

Thanks I didn't realise you has a custom board def for arduino, just downloaded the library directly!
