### ISSUE TITLE
Question about AS5600 I2C communication-The time difference between Read High and Low Byte cause a error

### ISSUE THREAD

**Issue by Dark-Guan** [uStepper/uStepper#4]
I don't use uStepper,but I build a similar one and I use AS5600 too.

Actually, I come across a problem,about read the Angle of AS5600.

uint16_t uStepperEncoder::readTwoBytes(uint8_t addr)
{
    uint16_t retVal;
    uint8_t low;

```
/* Read Low Byte */
Wire.beginTransmission(ENCODERADDR);
Wire.write(addr);
Wire.endTransmission();
Wire.requestFrom(ENCODERADDR, 1);
while(Wire.available() == 0);
retVal = (uint16_t)Wire.read();

/* Read High Byte */  
Wire.beginTransmission(ENCODERADDR);
Wire.write(addr + 1);
Wire.endTransmission();
Wire.requestFrom(ENCODERADDR, 1);

while(Wire.available() == 0);

low= Wire.read();

retVal <<= 8;

return retVal | (uint16_t)low;
```

}

It seems uStepper use this function to  get the Angle of the AS5600.

Reading High byte and Reading Low Byte is sparated. So, If the Motor is Runing When processor reads Angle of As5600 through I2C, the High Angle byte and the Low one is changing.
When Read the High one ,the Low is changing ,
For example: 

At a time
ANGLE is 0010 0000 0000
Read the High byte is 0000 0010 
But before read the low byte  
the ANGLE became 0000 1111 1111
Read the low byte ,the result will be 1111 1111,

The error is 1111 1111  = 255 .
it means there is a hop of the value.

I want to know,If you can Handle the problem.

**Comment by uStepperOld** [comment]
Hi Dark-Guan.

Do you mean that the high and low byte of the angle read from the encoder does not match within the sample period?

Can you elaborate on this?

**Comment by Dark-Guan** [comment]
Hi uSteper
Thanks for your replay.
I find this problem ,And I give up the AS5600 .

**Comment by Dark-Guan** [comment]
I have compared all the product of AMS Magnetic Position Sensors, It seems the ones support digital angle (interface) or AB(ABI) are more suitable for the accurate position detecting for motor.

**Comment by uStepperOld** [comment]
We dont do it like this in the new version of the library, since we had to write a whole new I2C class to replace the one in arduino, so what you are describing cannot happen in the new library.

i have never experienced this issue, with either the old or the new code.

Have you experienced this problem, or are you just afraid it might happen?

**Comment by Dark-Guan** [comment]
Yse,I have experenced this problem too.
It seems AS5600 does not lock the Angle Register (either the high and the low),when sends the the data,If it is ture,there is no way to keep the position messsage right  all the time ,espercially when the motor is running,I build a close-loop controlled motor driver use this Chip,but the error is too bigger.
If you have solved the problem?

**Comment by Dark-Guan** [comment]
I will try AS5601 and AS5145B ,I think they will be better.

**Comment by uStepperOld** [comment]
okay. However this problem can not happen if the two bytes are read back to back, meaning that instead of closing the I2C bus after the first byte has been read, you just read the next byte straight away.

This way both bytes has been transferred over the I2C port faster than the internal sampling frequency of 6.6kHz inside the AS5600 chip. (Here i assume you use 400kHz or higher I2C clock)

**Comment by Dark-Guan** [comment]
Yes,I am reading your newest code.
It seems I should read the As5600 datasheet again.
Thanks for your replay and advice very much,I will try your method

**Comment by Dark-Guan** [comment]
I have a question again,Can you tell me where do you find the message of the internal sampling frequency of 6.6kHz inside the AS5600 chip.

**Comment by uStepperOld** [comment]
It is listed in the datasheet of the AS5600

**Comment by Dark-Guan** [comment]
I test your method today,There is a little hop still ,no mater when disable the timer1 or not during read the angle.
I want to report this to you.
Thanks very much for your reply!

**Comment by IanSC** [comment]
try reading the 2 bytes together:
```
word AMS_5600::readTwoBytes(int addr)
{
  Wire.beginTransmission(_ams5600_Address);
  Wire.write(addr);
  Wire.endTransmission();
  Wire.requestFrom(_ams5600_Address, 2);
  while (Wire.available() < 2);
  
  int high = Wire.read();
  int low = Wire.read();
  return ( high << 8 ) | low;
}
```
